import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useTodoItems from '../utils/useTodoItems'
import TodoItem from '../components/TodoItem'
import { TodoItem as TodoItemType } from '../types/data'

type Props = {
  todoItems: TodoItemType[]
}

export const getStaticProps: GetStaticProps<Props> = async() => {

  const { getTodoItems } = useTodoItems()
  return {
    props: {
      todoItems: getTodoItems()
    }
  }
  
}

const Home: NextPage<Props> = ({ todoItems }) => {
  return (
    <div className="py-0 px-8">
      <Head>
        <title>react-todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Type what you wanna do.
        </p>

        <input
          className='mx-4 mb-16 w-2/5 text-5xl p-4
            border-b-4 border-zinc-500 outline-none text-zinc-500 italic
            placeholder-zinc-300 placeholder:italic'
          type="text" 
          placeholder='e.g. Buy tomato'/>

        <div className="flex items-center justify-center flex-col max-w-3xl">
          {todoItems.map( (todoItem, i) => {
            return (
              <TodoItem 
                todoItem={todoItem}
                key={i}/>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
